### ISSUE TITLE
Interfejs ISender i jego użycie

### ISSUE THREAD

**Issue by JakubBilski** [MINI-IO/IO-project-game#101]
W jaki sposób wyglądałoby korzystanie z Descriptorów w Communicator, skoro SendMessage nie przyjmuje argumentów? Obecna specyfikacja jest dosyć pogmatwana - SendMessage() potrzebuje Descriptora w Communicator, a nie potrzebuje go w Agent. Czy lepszym rozwiązaniem nie byłby słownik <int, ISender> w Communicator? Każdy Agent miałby ISender odpowiedzialny za komunikację tylko z nim, klasa Descriptor nie byłaby nigdzie potrzebna, a użycie SendMessage w Communicator stałoby się podobne do użycia SendMessage z Agenta. Ten drugi podczas konfiguracji przyjmuje, jak rozumiem, parametry sieciowe communication servera, skoro wie, gdzie domyślnie wysyłać wiadomości. Na podobnej zasadzie podczas dołączania nowych Agentów w Communicator tworzone byłyby nowe ISendery, odpowiedzialne za komunikację z poszczególnymi Agentami.
Nowy diagram wyglądałby jakoś tak (użyłem Painta, proszę się nie śmiać)
![proposal](https://user-images.githubusercontent.com/47048420/76628443-05075b00-653d-11ea-975b-a4f8490cf460.jpg)
Czy to ma sens, co napisałem?

**Comment by BartoszChrostowski** [comment]
# Odradzam używania modeli z diagramów klas

Są one jedynie **poglądowe** i ich głównym celem było spełnienie oczekiwań na IO1. Trzymanie się jednego modelu, nie dostosowując go do nowych, wcześniej nieodkrytych, subtelności, jest podejściem zgubnym. Nie zamierzamy też utrzymywać wspólnego modelu dla 15(?) drużyn. To co musi być identyczne to interfejsy wystawiane przez moduły (wiadomości i spełniane przez nie kontrakty).
Tworzenie tak dokładnych diagramów klas, przed implementacją, na pewno nie jest zwinne, w szczególności jeśli mają one być na tyle granularne, że tak na prawdę przedstawiają implementację, a nie ideę :(

**Comment by BartoszChrostowski** [comment]
Odpowiadając na pytanie, zróbcie tak, jak wam się podoba i jakie zadanie jest najwygodniejsze w technologii przez was wybranej.

**Comment by JakubBilski** [comment]
Super, dzięki
