### ISSUE TITLE
Brak dostępu do fragmentów w TaskField  PickUp(Player)  

### ISSUE THREAD

**Issue by Solzan** [MINI-IO/IO-project-game#104]
public bool PickUp(Player) 
"Metoda abstrakcyjna, która podnosi fragment z planszy i przypisuje go do gracza" 

Jeśli na danym polu jest fragment, Player podnosi go metodą void SetHolding(Piece) która przypisuje graczowi fragment, a dostęp do fragmentów  z private HashSet<AbstractPiece> pieces  klasy AbstractField jest zabroniony w TaskField, która po AbstractField  dziedziczy ponieważ pieces  jest private.

**Comment by Dragemil** [comment]
To duplikat #101, zamykam.
