### ISSUE TITLE
teamID w konfiguracji GM

### ISSUE THREAD

**Issue by kmltdr** [MINI-IO/IO-project-game#107]
https://github.com/MINI-IO/IO-project-game/blob/ad10d6a9dded2dbc435dda674f77832c7839bb94/Dokumentacja/Konfiguracje/resources/GM.jsonc#L4
https://github.com/MINI-IO/IO-project-game/blob/ad10d6a9dded2dbc435dda674f77832c7839bb94/Dokumentacja/Konfiguracje/resources/GMConfig.json#L4
Co oznacza ta liczba?

**Comment by BartoszChrostowski** [comment]
Nic nie znaczy, naprawione w v1.2
