### ISSUE TITLE
Czas kary

### ISSUE THREAD

**Issue by stankevichea** [MINI-IO/IO-project-game#108]
Jak było powiedziano w jednym z issues zakładamy, że agent będzie sam mierzył czas kary. To wtedy po co wiadomość od GM " Nie odczekanie kary"?

**Comment by Rashair** [comment]
Bo to niezależne moduły. To że jest to w założeniu, to nie znaczy, że nie pojawią się agenci, którzy będą próbowali obejść zasady.
**Game Master** odpowiada za zapewnienie przestrzegania zasad. Więc jeżeli jakiś agent będzie chciał  oszukiwać to dostanie właśnie tę wiadomość

**Comment by stankevichea** [comment]
> Bo to niezależne moduły. To że jest to w założeniu, to nie znaczy, że nie pojawią się agenci, którzy będą próbowali obejść zasady.
> **Game Master** odpowiada za zapewnienie przestrzegania zasad. Więc jeżeli jakiś agent będzie chciał oszukiwać to dostanie właśnie tę wiadomość

Ale w jaki sposób GM zrozumie, że Agent oszukał? Jeżeli GM nie mierzy czas kary

**Comment by BartoszChrostowski** [comment]
Było powiedziane, że GM nie odpowiada za informowanie Agenta o czasach, pierwotna wersja zakładała synchronizację czasu między modułami, ale to było głupie z naszej strony

GM mierzy czas, żeby egzekwować kary.
Agent też sobie mierzy czas na własną rękę, żeby nie wysyłać błędnych zapytań (może powinnismy nałożyć kary za błąd zapytania 🤔)
