### ISSUE TITLE
Kara

### ISSUE THREAD

**Issue by stankevichea** [MINI-IO/IO-project-game#109]
Jeżeli agent poprosił o wykonanie ruchu i GM mu odmówił, to agent czeka czas kary czy nie?

**Comment by Rashair** [comment]
Nie ma nic o tym
![image](https://user-images.githubusercontent.com/33404585/76898242-9f490500-6895-11ea-89d8-bfabbd5b4106.png)
Stąd nie ma takiej kary.

Prawdopodobnie GM powinien się jakoś zabezpieczyć przed zbyt dużym napływem błędnych zapytań i przez jakiś odrzucać zapytania takiego gracza wysyłając niezdefiniowany błąd.

**Comment by BartoszChrostowski** [comment]
Jeśli była próba wykonania błędnej akcji np. wejście na pole na której jest inny agent, wykonania akcji podczas innej kary...

> Prawdopodobnie GM powinien się jakoś zabezpieczyć przed zbyt dużym napływem błędnych zapytań

Może na serwerze jakiś sztuczny filtr wrzucić, który by za częstych zapytaniach zacząłby je czytać rzadziej. Ale nie wiem w sumie.
