### ISSUE TITLE
Błąd odłożenia a błąd położenia

### ISSUE THREAD

**Issue by kmltdr** [MINI-IO/IO-project-game#111]
Czym różnią się od siebie te błędy i kiedy mogłyby się zdarzyć?

![image](https://user-images.githubusercontent.com/33494817/76085457-5ef2a880-5fb2-11ea-84bf-b1c6b32b96fe.png)
_Originally posted by @stankevichea in https://github.com/MINI-IO/IO-project-game/issues/68#issuecomment-595747266_

**Comment by BartoszChrostowski** [comment]
Pierwsze to pewnie było podniesienie
