### ISSUE TITLE
Więcej niż jeden kawałek na jednym polu

### ISSUE THREAD

**Issue by marcelwenka** [MINI-IO/IO-project-game#112]
Czy na jednym polu nie powinien znajdować się maksymalnie jeden kawałek? W Issue #75 napisałeś Kasi, żeby wybierać obojętnie, ale co jeśli na jednym polu leży sham i normalny kawałek? Losować, ostatni położony?

**Comment by BartoszChrostowski** [comment]
### Musi być możliwość odłożenia więcej niż jednego kawałka, na dowolne pole.

Do Kasi odpisałem, czy obojętnie czy będą znikać czy będą przetrzymywane w przypadku odłożenia kawałka w goal area (my trzymamy wszystkie położone, bo potencjalnie może się dla gui przydać informacja, ale równie dobrze można trzymać jakiś stan i po odłożeniu na goal area i znikać te kawałki)

![image](https://user-images.githubusercontent.com/32818862/77222564-b36e5a00-6b54-11ea-994d-187bfc9004ff.png)
Z tym goal field nie wiem czemu tak zostało napisane, to nie jest prawda.
