### ISSUE TITLE
Brak danych w odpowiedzi od GM

### ISSUE THREAD

**Issue by piotr147** [MINI-IO/IO-project-game#113]
W jaki sposób agent się dowiaduje, że cel nie został osiągnięty?

![screen1](https://user-images.githubusercontent.com/48105497/76907685-25ba1280-68a7-11ea-910d-8a7b47bdc351.png)
![screen2](https://user-images.githubusercontent.com/48105497/76907693-2ce12080-68a7-11ea-94b2-7f979e4c9680.png)

**Comment by BartoszChrostowski** [comment]
Id wiadomości nie będące błędem.
Do postaram się ogarnąć wiadomości  najbliższym czasie i dodać correlation id którego nie ma

**Comment by BartoszChrostowski** [comment]
Nie zrozumiałem pytania, odpowiedziałem w #119
