### ISSUE TITLE
Id wiadomości

### ISSUE THREAD

**Issue by stankevichea** [MINI-IO/IO-project-game#117]
Po co są id wiadomości?

**Comment by BartoszChrostowski** [comment]
Żeby wiedzieć jaką metodę wywołać, oraz pośrednio co znajduje się w payload
Z perspektywy czasu uważam, że mógł być to po prostu string z nazwą procedury (albo dosłownie implementacja json rpc) ale trudno

**Comment by stankevichea** [comment]
> Żeby wiedzieć jaką metodę wywołać, oraz pośrednio co znajduje się w payload
> Z perspektywy czasu uważam, że mógł być to po prostu string z nazwą procedury (albo dosłownie implementacja json rpc) ale trudno

a w którym polu wpisujemy to id?

**Comment by BartoszChrostowski** [comment]
W polu `messageID` w kopercie
![image](https://user-images.githubusercontent.com/32818862/77115246-4a8cc200-6a2e-11ea-994a-1209115b93d7.png)

**Comment by BartoszChrostowski** [comment]
nie powinno być timeSent w required oczywiście, to jest błąd w def. wiadomości, w wolnej chwili się tym zajmę

**Comment by stankevichea** [comment]
> nie powinno być timeSent w required oczywiście, to jest błąd w def. wiadomości, w wolnej chwili się tym zajmę

oki, i jeszcze nie wszędzie jest to messageID

**Comment by BartoszChrostowski** [comment]
Każda wiadomość opakowana jest w kopertę
![image](https://user-images.githubusercontent.com/32818862/77115960-94c27300-6a2f-11ea-9215-454d5837fbfb.png)
Czyli każda wiadomość jest postaci

`{"messageID": 4,"agentID": 635, "payload": { "data": 123,"moreData": "asdf" }}`

gdzie payloady są wyspecyfikowane w podsekcjach 6.2 i 6.3

Może nie jest to wystarczająco jasno napisane. Jutro na serio się za to wezmę
