### ISSUE TITLE
Discovery

### ISSUE THREAD

**Issue by Solzan** [MINI-IO/IO-project-game#118]
Co zwracamy w przypadku gdy zwracane pola ( np. DistanceN) należą do Goals area lub wychodzą poza planszę?

**Comment by BartoszChrostowski** [comment]
Będziemy wstawiać null. Zmienię te pola na nieobowiązkowe w jsons

![image](https://user-images.githubusercontent.com/32818862/77222225-9be1a200-6b51-11ea-8b7f-1793a7d92f46.png)

Related #115

**Comment by piotr-onyszczuk** [comment]
dlaczego dla GoalArea mielibyśmy zwracac cos specjalnego? stamtąd też moze byc jakaś odległość

**Comment by BartoszChrostowski** [comment]
Nie zwróciłem na to uwagi, oczywiście:
poza planszą/nie ma nic na planszy - brak wartości
wpp - jakaś wartość
