### ISSUE TITLE
Startowa pozycja agentów

### ISSUE THREAD

**Issue by BartekTr** [MINI-IO/IO-project-game#124]
Czy przy inicjalizacji planszy agenci mają mieć startowe pozycje dowolnie na planszy (oczywiście poza goal area przeciwnika) czy tylko w swoim goal area, bądź tylko na odpowiedniej połowie planszy? Czy pozycje startowe drużyn powinny być symetryczne?

**Comment by BartoszChrostowski** [comment]
Obojętnie
