### ISSUE TITLE
Penalties w wiadomości o rozpoczęciu gry 105

### ISSUE THREAD

**Issue by marcelwenka** [MINI-IO/IO-project-game#125]
W wiadomości o rozpoczęciu gry (105) w penalties jest destroyPiece, którego za to nie ma w konfiguracji GameMastera. Czy w takim razie zniszczenie kawałka podlega karze, czy nie?

Wszystkie kary są typu string, chyba spokojnie można je zamienić na integer.

I ostatnie - jest jedna kara dotycząca wymiany informacji przez zawodników: "informationExchange", podczas gdy powinny chyba być dwie: "ask" i "response".

**Comment by BartoszChrostowski** [comment]
> I ostatnie - jest jedna kara dotycząca wymiany informacji przez zawodników: "informationExchange", podczas gdy powinny chyba być dwie: "ask" i "response".

Można rozbić na dwie różne wymiary kar, ale po co

**Comment by marcelwenka** [comment]
> Można rozbić na dwie różne wymiary kar, ale po co
To w takim razie trzeba by też w konfiguracji GMa zmienić askPenalty i responsePenalty na informationExchangePenalty, tak żeby było bardziej uniwersalnie

**Comment by marcelwenka** [comment]
> Można rozbić na dwie różne wymiary kar, ale po co

To w takim razie trzeba by też w konfiguracji GMa zmienić askPenalty i responsePenalty na informationExchangePenalty, tak żeby było bardziej uniwersalnie
