### ISSUE TITLE
Więcej niż jeden kawałek na jednym polu

### ISSUE THREAD

**Issue by piotr-onyszczuk** [MINI-IO/IO-project-game#135]
Doprecyzuję #112. Co jeśli odkładamy kawałek w TaskField i tam leży już jakiś kawałek? Nie byłoby prościej gdyby **odkładany przez gracza kawałek zawsze był wyłączany z rozgrywki** (nie tylko w polu bramkowym)?

![1](https://user-images.githubusercontent.com/36960410/77819263-d317fc00-70d9-11ea-9eff-3ea3cb9facdd.png)

Rodzi to problem wspomniany w wymienionym zagadnieniu. Co jeśli w jenym będą leżały sham i normal piece?

**Comment by marcelwenka** [comment]
Odpowiedź masz w Issue #75, dokumentacja tego nie doprecyzowuje, więc pozostaje w gestii programistów Game Mastera. Możecie zwracać:
- ostatni z listy,
- losowy,
- najpierw normalne kawałki, potem shamy,
- dowolne kombinacje powyższych.

Nie widzę powodu, dlaczego miałyby być wyłączane z gry, może któryś zespół postanowi podzielić swoich Playerów na tych, którzy przynoszą kawałki pod Goal Area (na ostatnie pole Task Area) i na tych, który podnoszą z tego ostatniego pola i odkładają w Goal Area, wtedy nie byłoby potrzeby komunikować wszystkim innym graczom, że dane pole w Goal Area zostało już sprawdzone.
