### ISSUE TITLE
Sens akcji niszczenia fragmentu

### ISSUE THREAD

**Issue by piotr-onyszczuk** [MINI-IO/IO-project-game#136]
Jaki jest sens akcji niszczenia fragmentu - "Zapytanie o zniszczenie fragmentu" skoro

![image](https://user-images.githubusercontent.com/36960410/77819331-62251400-70da-11ea-821c-837dc16f2785.png)

W jakiej innej sytuacji gracz mógłby chcieć zniszczyć fragment?

**Comment by krzysztof-wozniak** [comment]
Przypuszczalnie trzyma kawałek, wchodzi na pole z kawałkiem, więc niszczy i podnosi, żeby przeciwnik nie wziął
