### ISSUE TITLE
Niezdeﬁniowany błąd

### ISSUE THREAD

**Issue by JakubBrojacz** [MINI-IO/IO-project-game#138]
Schema do wiadomości "niezdefiniowany błąd" wymaga podania pozycji gracza i faktu czy trzyma kawałek. A co w sytuacji kiedy błąd polega na przykład na podaniu niewłaściwego agentID? Albo na wysłaniu wiadomości w złym formacie którego GM nie potrafi sparsować?

**Comment by BartoszChrostowski** [comment]
Nie przewidujemy takich komunikatów błędu

**Comment by JakubBrojacz** [comment]
To co należy robić w takiej sytuacji?
