### ISSUE TITLE
Typ messageID

### ISSUE THREAD

**Issue by MisterSadness** [MINI-IO/IO-project-game#141]
messageID w schemach z dokumentacji jest określone jako int, a według tabelki może mieć wartość na przykład 001. Nie byłoby lepszym rozwiązaniem zmienienie typu na stringa / wartości na prawidłowe liczby? 

1. Atm nie ma różnicy czy jest tam 001 czy 1
2. Nie widzę powodu, żeby specjalnie wypisywać inty w taki sposób

**Comment by BartoszChrostowski** [comment]
> Atm nie ma różnicy czy jest tam 001 czy 1
Tak
