### ISSUE TITLE
Literówka w wiadomości na start gry

### ISSUE THREAD

**Issue by Zackere** [MINI-IO/IO-project-game#142]
![image](https://user-images.githubusercontent.com/40472142/78042811-d7127b00-7372-11ea-8805-be96e1820866.png)
Pole w penalties powinno się nazywać chckForSham (chyba że to specjalnie to przepraszam)
oraz w wiadomościach id drużyny jest referowane jako 'teamId' co burzy konwencję *ID. Czy to celowy zabieg?

**Comment by marcelwenka** [comment]
Szczególnie, że w konfiguracji Agenta jest teamID a nie teamId.

**Comment by kmltdr** [comment]
checkForSham poprawiłem w #110
