### ISSUE TITLE
Możliwość pomocy w naprawie dokumentacji

### ISSUE THREAD

**Issue by Zackere** [MINI-IO/IO-project-game#144]
W jaki sposób można się przyczynić do rozwoju dokumentacji? Domyślam się po ilości issue oznaczonych jako 'help wanted' że osoby trzecie mogłyby tworzyć branche i proponować jakieś konkretne zmiany, jednak to niemożliwe.

**Comment by BartoszChrostowski** [comment]
[pr](https://github.com/MINI-IO/IO-project-game/pulls)

Ja nie mogę zupełnie czasu znaleźć na to.

**Comment by Zackere** [comment]
Tylko nie można pushować branchy swoich żeby zrobić dla nich pull request

**Comment by Zackere** [comment]
Chyba ogarnąłem jak.

**Comment by BartoszChrostowski** [comment]
Workflow klasyczny jak na GH
PR z forka. Z tego co mi się wydaje jest ograniczona ilość osób którą mogę dodać do organizacji
