### ISSUE TITLE
Wymiana informacji

### ISSUE THREAD

**Issue by JakubBrojacz** [MINI-IO/IO-project-game#151]
Czy można kilka razy poprosić o wymianę informacji tego samego agenta zanim on wyśle odpowiedź?
Czy wtedy zapytany gracz może odpowiedzieć tylko raz, czy tyle razy ile go poproszono?

Z niewspieranych już diagramów klas wynika, że można kilka razy poprosić, ale zapytany gracz będzie mógł odpowiedzieć tylko raz (wykorzystanie struktury `set` do przechowywania `LegalKnowledgeReplies`).

**Comment by BartoszChrostowski** [comment]
Nie widzę powodu żeby to było nielegalne
