### ISSUE TITLE
Dokładność timestampów w wiadomościach

### ISSUE THREAD

**Issue by metiulekm** [MINI-IO/IO-project-game#58]
W adapterze pojawiają się pola `timeSent` i `waitUntil`. Jak dokładne muszą być te daty? Czy zakładamy że komputer na którym działa którykolwiek z modułów ma dokładnie ustawiony zegar?

**Comment by BartoszChrostowski** [comment]
Nie wiem jak to zrobić najprościej, wymuszenie synchronizacji czasu przed odpaleniem programu wydaje się dość prymitywne, ale nie dodające złożoności z synchronizacją w trakcie gry.

**Comment by metiulekm** [comment]
> wymuszenie synchronizacji czasu przed odpaleniem programu wydaje się dość
prymitywne, ale nie dodające złożoności z synchronizacją w trakcie gry

Nie wystarczy, co jeśli odpali się systemowy NTP w połowie rozgrywki?

IMO stosowanie timestampów realtime'owych jest złym pomysłem, rozważyłbym
przejście na monotoniczne i zaakceptowanie tego, że między modułami będzie
stała różnica w wartości zegara.

**Comment by metiulekm** [comment]
TS'y RT'owe są ogólnie kiepskim pomysłem, bo jeśli powiedzmy czas systemowy miałby cofnąć się o godzinę w trakcie działania systemu, to system wywali się w efektowny sposób nawet, jeśli to zsynchronizujemy.

Użycie TS'ów monotonicznych wymaga też zmiany formatu w wiadomościach JSON.

**Comment by BartoszChrostowski** [comment]
To zostanie zmienione, cała odpowiedzialność będzie przerzucona na Agenty, one będą musiały na podstawie informacji o karach same liczyć za ile wysłać wiadomość. Zmienione będą wiadomości. Zdefiniowane zostanie dokładnie, jaka będzie dokładność tych czasów kar w konfiguracji
