### ISSUE TITLE
Literówki i błędy

### ISSUE THREAD

**Issue by Rashair** [MINI-IO/IO-project-game#60]
1.	podstwaie -> podstawie
2.	rozgrwki -> rozgrywki
3.	specjale -> specjalne
4.	`havePiece` -> `hasPiece`
5.	decuduje -> decyduje
6.	`messageCorellationId` -> `messageCorrelationId`
7.	`Knowleadge` -> `Knowledge` (w polach i funkcjach GM)
8.	`Message SenderService` -> `MessageSenderService`
9.	informacjie -> informacji

**Comment by metiulekm** [comment]
> Odbywa się poprzez połczenie się z Serwerem Komunikacyjnym

połczenie → połączenie

**Comment by moskal-alicja** [comment]
#102
