### ISSUE TITLE
Akcja "sprawdzenia wybranego pola"

### ISSUE THREAD

**Issue by Rashair** [MINI-IO/IO-project-game#61]
![image](https://user-images.githubusercontent.com/33404585/75764953-f6e85c00-5d3e-11ea-8d23-319f45bd1ede.png)
Nie znalazłem więcej odniesień do tej akcji, tych informacji nie ma w odpowiedzi na akcję `Discovery`. Czy w takim razie to, czy pole jest Goalem może zostać odkryte przez `Discovery`?

**Comment by Rashair** [comment]
Ktoś?

**Comment by BartoszChrostowski** [comment]
Wydaje mi się że pozostałość jakaś. Do usunięcia.

**Comment by JakubBrojacz** [comment]
Zauważyłem, że metoda `Put(AbstractField)` z `ShamPiece` ma opis:
```
Implementacja odwiedzaja˛cego, wywołuje PutSham() z AbstractField, je´sli dane pole było bramkowe przekazuje te˛ informacje˛ do gracza.
```
I w ten sposób chcieliście odkrywać czy pole jest Goalem. 

Powiązane z #96

**Comment by Rashair** [comment]
> Zauważyłem, że metoda `Put(AbstractField)` z `ShamPiece` ma opis:
> 
> Implementacja odwiedzającego, wywołuje PutSham() z AbstractField, jeśli dane pole było bramkowe przekazuje tę informację do gracza.
> 
> I w ten sposób chcieliście odkrywać czy pole jest Goalem.
> 
> Powiązane z #96

Jeśli tak jest to to jest błąd. W oryginalnej specyfikacji było wyraźnie napisane, że agent nie otrzymuje żadnych informacji po położeniu shamPiece

**Comment by BartoszChrostowski** [comment]
> The risk of doing a task is simulated by a probability that a given piece
is a sham. The agent can discover that fact either by testing a piece (which it
currently holds) or by placing it in the goal area and not receiving any feedback,
about that field being a part of a project goal or not.

Masz rację
