### ISSUE TITLE
Niekonsekwencje i błędy w nazwach pól

### ISSUE THREAD

**Issue by Rashair** [MINI-IO/IO-project-game#62]
- `portAgentow` w 6.1, jeżeli trzymamy się angielskiego w poprzednich wiadomosciach JSON, to tu również powinno tak być -> zamiana na portAgents
- `playerInfo` w klasie Field jest niewłaściwie nazwany, nazwa sugeruje, że są to jakieś informacje o graczu, gdy właściwie jest to tylko bool informujący o obecności innego gracza – powinno zostać zamienione na np. `isTakenByOtherPlayer`. Dodatkowo skąd miałaby się wziąć ta informacja? Akcja `Discovery` nie zwraca takich danych.
- `holding` w klasie Player jest źle nazwane, sugeruje zmienną typu bool, podczas gdy jest to Piece trzymany przez gracza - powinno zostać zamienione na  `piece` / `heldPiece`
- `LockedTill` w klasie Player powinno zaczynać się z małej litery tak jak reszta jego pól, jak również w kontraście, metoda `tryLock` powinna zaczynać się z dużej
- `WhosHere` w AbstractField powinno zostać nazwane po prostu `player` - pole nie powinno być pytaniem, tylko rzeczownikiem
- Czasem używana jest nazwa `bool`, a czasem `boolean` - powinna zostać wybrana jedna konwencja
- `LegalKnowleadgeReplies` w GM powinno być z małej litery

**Comment by BartoszChrostowski** [comment]
To pisało wiele osób i niestety nigdy się nad tym nie skupiliśmy, aby były spójne
Osobiście nie wierzę, że da się utrzymać spójny model dziedziny z dokumentacji i implementacji, bo projekt nie jest dojrzały i poznany model nie jest jeszcze dogłębny, więc będzie dużo zmian, a zmieniane dokumentacji, za każdym razem gdy odkryjemy nowy fragment dziedziny, będzie męczące dla wszystkich, ponieważ wiele zespołów jest od niej zależne, dlatego optuję, żeby nie skupiać się na diagramach klas i tratować je jedynie jako sugestię.

**Comment by BartoszChrostowski** [comment]
Jednocześnie postaram się do następnego wydania uspójnić to co jest.

**Comment by Rashair** [comment]
Rozumiem, a powiesz skąd się bierze `playerInfo` w klasie Field (punkt 2)?

**Comment by jakub-drak-sbahi** [comment]
Agent może stwierdzić czy pole jest zajęte próbując na nie wejść.
