### ISSUE TITLE
MoveHere(Player) w AbstractField

### ISSUE THREAD

**Issue by Rashair** [MINI-IO/IO-project-game#63]
`MoveHere(Player)` w AbstractField – zwraca bool, sugeruje to że akcja może się nie powieść, czy logika walidacji ruchu nie powinna być obecna gdzieś w GM, a nie w AbstractField? 

Natomiast metoda `PickUp` w AbstractField jest typu void, a powinna być typu bool, tak jak w klasach dziedziczących.

**Comment by BartoszChrostowski** [comment]
> czy logika walidacji ruchu nie powinna być obecna gdzieś w GM, a nie w AbstractField?

Na mój obecny stan wiedzy taki model jest lepszy niż trzymanie tej logiki w GM, ponieważ jak w np #66 będziemy chcieli wprowadzić specjalny typ pola, który sprawdza, czy drużyna się zgadza, aby nie pozwolić na wejście na goal area przeciwnika, to będzie to wprowadznie nowego pola, wywołującego logikę bazowej klasy oraz sprawdzenie czy drużyny się zgadzają, ale tak jak mówiłem model nigdy nie był implementowany i w trakcie kolejnych iteracji refaktoryzacji na pewno wyłoni się lepszy (może to co napisałem to jakiś dekorator by był lepszy jednak)

> Natomiast metoda PickUp w AbstractField jest typu void, a powinna być typu bool, tak jak w klasach dziedziczących.

Będzie poprawione przy okazji.
