### ISSUE TITLE
Niepotrzebna flaga lidera w waitingPlayers

### ISSUE THREAD

**Issue by Rashair** [MINI-IO/IO-project-game#64]
![image](https://user-images.githubusercontent.com/33404585/75766429-6bbc9580-5d41-11ea-8b26-7d1407595ada.png)
--
![image](https://user-images.githubusercontent.com/33404585/75766461-7d9e3880-5d41-11ea-86b1-9829d5496208.png)
--
![image](https://user-images.githubusercontent.com/33404585/75766478-84c54680-5d41-11ea-8c71-dba942db3c77.png)
--
Czyli jednocześnie następuje zablokowanie, a wiadomość lidera wciąż jest kolejkowana?
Czy w takim razie nie powinny być kolejkowane tylko te wiadomości, które nie pochodzą od lidera, a logika obsługi wiadomości lidera powinna być natychmiastowa?

**Comment by jakub-drak-sbahi** [comment]
#67
