### ISSUE TITLE
Nieprawdziwe informacje w komunikacji

### ISSUE THREAD

**Issue by Rashair** [MINI-IO/IO-project-game#65]
W wymianie informacji jest wzmianka o tym, że `Udzielane informacje nie muszą być prawdziwe`.
Czy to znaczy, że gracze mogą się komunikować z graczami z innych drużyn? Po co mieliby to robić, jeżeli dostarczone informacje i tak mogłyby być fałszywe?
A jeśli nie, to w jakim celu gracz z tej samej drużyny miałby przesyłać fałszywe informacje?
Nie za bardzo widzę cel istnienia takiej opcji.

**Comment by metiulekm** [comment]
TBH nie da się wymusić tego żeby informacje były prawdziwe, ani sprawdzić czy są.

> Czy to znaczy, że gracze mogą się komunikować z graczami z innych drużyn? Po co mieliby to robić, jeżeli dostarczone informacje i tak mogłyby być fałszywe?

Rozkminialiśmy to z grupą i wymagania dra Okulewicza mówią o takiej opcji.

> Po co?

Dobre pytanie.

**Comment by metiulekm** [comment]
> TBH nie da się wymusić tego żeby informacje były prawdziwe, ani sprawdzić czy są.

W sumie, w tej chwili specyfikacja ściśle ogranicza zbiór przekazywanych danych do tych które są przekazywane przez GM. W takim wypadku GM mógłby przekazywać te dane bezpośrednio.

Osobną kwestią jest to, czy takie ograniczenie jest sensowne; zakres przekazywanych danych powinien IMO zależeć od strategii, a ta OFC nie może być wyspecyfikowana.

**Comment by BartoszChrostowski** [comment]
> Osobną kwestią jest to, czy takie ograniczenie jest sensowne

To nie jest tak, że dokumentacja jest absolutna i skończona, jeśli się zdecydujemy, można to ograniczenie zdjąć

**Comment by BartoszChrostowski** [comment]
> Czy to znaczy, że gracze mogą się komunikować z graczami z innych drużyn?

Tak.

> Po co mieliby to robić, jeżeli dostarczone informacje i tak mogłyby być fałszywe?

Nie wiem, ale nie chciałem (w trakcie pisania dokumentacji) wprowadzać sprawdzania czy informacje są poprawne przez GM, ponieważ to mogłoby być nietrywialne.
