### ISSUE TITLE
Identyczne projekty i wejście na goal area drużyny przeciwnej

### ISSUE THREAD

**Issue by Rashair** [MINI-IO/IO-project-game#66]
W dokumentacji jest informacja, że `Projekty generowane są na początku rozgrywki, identyczne dla każdej drużyny`. -> projekty mają dokładnie ten sam kształt?
Dodatkowo `Agent może przebywać na dowolnym polu planszy niezajętym przez innego Agenta`. -> również na goal area drużyny przeciwnej?

Jeżeli oba moje wnioski są prawdziwe, to możliwe jest zdobycie swojego pola projektu przez gracza, a następnie całkowite zablokowanie analogicznego pola u drużyny przeciwnej poprzez zajęcie go i brak ruchu. Czasem mogłoby to doprowadzić do zapętlenia gry.

**Comment by BartoszChrostowski** [comment]
Jestem za zakazaniem wejścia na pole bramkowe przeciwnika.
