### ISSUE TITLE
Uściślenie słownika

### ISSUE THREAD

**Issue by stankevichea** [MINI-IO/IO-project-game#68]
Czy słowo "kawałek" jest tym samym co "fragment" w dokumentacji? Jeżeli nie, to jaka jest różnica?

**Comment by BartoszChrostowski** [comment]
Wydaje mi się, że tak.
Niech ktoś jeszcze potwierdzi @jakub-drak-sbahi  @moskal-alicja

**Comment by stankevichea** [comment]
I czym będą się różnią "Błędne odłożenie kawałka" i "Błędne położenie kawałka"

**Comment by jakub-drak-sbahi** [comment]
> Wydaje mi się, że tak.
> Niech ktoś jeszcze potwierdzi @jakub-drak-sbahi @moskal-alicja

Tak
