### ISSUE TITLE
Odległość do kawałka

### ISSUE THREAD

**Issue by stankevichea** [MINI-IO/IO-project-game#69]
W dokumentacji jest napisane, że wchodząc na pole gracz otrzymuje odległość od najbliższego kawałka.

-  A co jeżeli ten kawałek znajduje się na polu bramkowym? Będziemy nadal otrzymywać odległość do tego kawałka?

- A jeżeli cel został spełniony i kawałek leży na tym miejscu, no odległość do niego też będzie pokazywana?

![dist](https://user-images.githubusercontent.com/33494817/76081693-f1427e80-5fa9-11ea-9df6-77f92cd3ee04.png)

**Comment by BartoszChrostowski** [comment]
Słuszna uwaga, powinna być obliczana odległość do najbliższego kawałka który da się podnieść.

**Comment by Rashair** [comment]
Chyba do zamknięcia
