### ISSUE TITLE
Generowanie  kawałków

### ISSUE THREAD

**Issue by stankevichea** [MINI-IO/IO-project-game#70]
W dokumentacji mamy :
- "Fragmenty generowane są przez Game Mastera co określony interwał czasowy i odkładane
na losowe pole zadań"
- "Akcja agenta może spowodować zmianę stanu planszy, w tym wygenerowanie nowego
kawałka jeśli akcja˛ było odłożenie fragmentu w polu bramkowym lub zniszczenie
go"

Czy nowe kawałki generowane co jakiś czas? Czy przy spełnieniu celu? Czy w obu przypadkach?

**Comment by BartoszChrostowski** [comment]
Usunięty zostanie interwał, nowe fragmenty będą generowane przez GM na odłożenie jakiegoś fragmentu w polu bramkowym lub zniszczenie.

**Comment by Rashair** [comment]
To znaczy, że ilość kawałków na planszy będzie stała?
