### ISSUE TITLE
Synchronizacja 

### ISSUE THREAD

**Issue by stankevichea** [MINI-IO/IO-project-game#71]
W jakim sensie synchronizacja z GM?
![sc](https://user-images.githubusercontent.com/33494817/76083068-0076fb80-5fad-11ea-844e-934f874fe3c8.png)

**Comment by BartoszChrostowski** [comment]
W kopercie o błędzie przekazywana jest informacja o położeniu i inne informacje o stanie gry, na ich podstawie agent może je uaktualnić, jeśli miał błędne.
