### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by stankevichea** [MINI-IO/IO-project-game#72]
"Game Master w graficznym interfejsie użytkownika prezentuje aktualny stan planszy. "
Czy to oznacza, że możemy pokazać widok planszy poszczególnych graczy, czy pokazujemy tylko globalny widok obserwatora?

**Comment by BartoszChrostowski** [comment]
Stan planszy gry. Moduł GM w naszej proponowanej implementacji, nie śledzi stanu wiedzy agentów.
