### ISSUE TITLE
Deadlock 

### ISSUE THREAD

**Issue by stankevichea** [MINI-IO/IO-project-game#76]
Co się stanie kiedy zostaną zablokowane 2 lidery, przez wzajemne wysyłanie zapytania o wymianę informacji?

**Comment by metiulekm** [comment]
Czy to aby na pewno jest możliwe? Jedna prośba powinna zablokować drugą, bo prośby przechodzą przez GM.

**Comment by JakubBrojacz** [comment]
`Akcje agentów wykonywane są asynchronicznie`
A czy to znaczy że GM przetwarza je asynchroniczne? Bo jeśli tak to taki deadlock chyba jest możliwy.

**Comment by BartoszChrostowski** [comment]
> Akcje agentów wykonywane są asynchronicznie

To jakiś głupi pomysł w ogóle, że padło takie założenie. Do wyrzucenia
