### ISSUE TITLE
Odłączenie modułów

### ISSUE THREAD

**Issue by stankevichea** [MINI-IO/IO-project-game#78]
"system powinien być niewrażliwy na ewentualne odłączenie się innych modułów, wykryć takie zachowanie i odpowiednio zareagować"
Na czym polega to wykrycie? Nie lepiej  prze odłączeniu się innych modułów kończyć działanie aplikacji?(Oprócz sytuacji kiedy się odłącza agent)

**Comment by Rashair** [comment]
![image](https://user-images.githubusercontent.com/33404585/76164631-c47c9b80-6150-11ea-8247-d8a3186b30d9.png)
Chyba właśnie tak jest to opisane

**Comment by metiulekm** [comment]
Potencjalny duplikat #59

**Comment by BartoszChrostowski** [comment]
> system powinien być niewrażliwy na ewentualne odłączenie się innych modułów, wykryć takie zachowanie i odpowiednio zareagować

Należy usunąć te wymaganie bo jest bardzo generyczne i faktycznie wprowadza w błąd. W przypadku braku komunikacji chcemy kończyć rozgrywkę. Można by się zastanawiać czy nad ponownym dołączeniem agenta, ale to by wprowadziło sporo potencjalnych problemów.

Obecnie pozostańmy przy scenariuszu, że każdy błąd komunikacji jest krytyczny i kończy działanie modułu.

**Comment by stankevichea** [comment]
> > system powinien być niewrażliwy na ewentualne odłączenie się innych modułów, wykryć takie zachowanie i odpowiednio zareagować
> 
> Należy usunąć te wymaganie bo jest bardzo generyczne i faktycznie wprowadza w błąd. W przypadku braku komunikacji chcemy kończyć rozgrywkę. Można by się zastanawiać czy nad ponownym dołączeniem agenta, ale to by wprowadziło sporo potencjalnych problemów.
> 
> Obecnie pozostańmy przy scenariuszu, że każdy błąd komunikacji jest krytyczny i kończy działanie modułu.

Nawet odłączenie się agenta?

**Comment by BartoszChrostowski** [comment]
Tak.
