### ISSUE TITLE
Opakowywanie adapterem

### ISSUE THREAD

**Issue by metiulekm** [MINI-IO/IO-project-game#86]
> Wiadomości wysyłane przez GM i Agentów opakowywane są w adapter opisujący kontekst wysyłanej wiadomości.

Z tego wynikałoby, że to GM i Agenci wpisują ten adapter. Jednak dalej jest napisane:

> Pole `agentID` uzupełniane jest przez serwer na podstawie jego własnego mapowania klientów na identyfikatory.

To w końcu jak to jest? Nadawca wpisuje `messageID`, a `agentID` zostawia `null`? Chyba jednak nie, bo inaczej CS mógłby nie wiedzieć gdzie wysłać wiadomość od GMa. Trzeba by to było uściślić. Swoją drogą, określenie "serwer" może zostać zrozumiane jako GM — to też warto by było uściślić.

Miałoby sens, żeby adapter między Agentem a CS był pozbawiony `agentID`.

**Comment by BartoszChrostowski** [comment]
Pole te nie jest oznaczone jako required.
