### ISSUE TITLE
Własne informacje w wymianie informacji

### ISSUE THREAD

**Issue by metiulekm** [MINI-IO/IO-project-game#87]
Wymiana informacji, jak sama nazwa wskazuje, jest wymianą między dwoma Agentami. Z tego powodu Agent o nią proszący powinien też wysłać własne informacje. Dokumentacja w tej chwili zdaje się tego nie wymagać.

**Comment by BartoszChrostowski** [comment]
Nie przewidywaliśmy takiego czegoś. Przewidywaliśmy tylko, zapytanie odpowiedź. W przypadku gdy miałoby być to w obie strony oba agenty musiałyby wysłać zapytanie do siebie nawzajem i i dostać odpowiedź.
