### ISSUE TITLE
Klasa Descriptor

### ISSUE THREAD

**Issue by Rashair** [MINI-IO/IO-project-game#89]
Przydałby się lepszy opis tego, czym jest deskryptor - jest to słabo rozpisane.
![image](https://user-images.githubusercontent.com/33404585/76173264-447d2280-619e-11ea-8536-76ff19a61bb1.png)

**Comment by BartoszChrostowski** [comment]
To abstrakcja na połączenie z agentem, obojętnie mi czy będzie to TCPClient z C# czy int z POSIX C
