### ISSUE TITLE
Port agenta

### ISSUE THREAD

**Issue by Zackere** [MINI-IO/IO-project-game#93]
Z konfuguracji CS wynika, że każdy agent nasłuchuje na tym samym porcie. Skąd agent wie, na którym porcie powinien słuchać? Nie jest to uwzględnione w jego konfiguracji a CS mógłby w trakcie dołączania graczy do rozgrywki zbierać informacje o tym, który agent jest na którym porcie.

**Comment by BartoszChrostowski** [comment]
> Z konfuguracji CS wynika, że każdy agent nasłuchuje na tym samym porcie.

W jaki sposób?
