### ISSUE TITLE
Ujednoznaczenie współrzędnych

### ISSUE THREAD

**Issue by BartoszChrostowski** [MINI-IO/IO-project-game#99]
<s>pierwsza współrzędna = x = wiersz

druga współrzędna = y = kolumna</s>

**Comment by Rashair** [comment]
y = wiersz = pierwsza współrzędna
 x = kolumna = druga współrzędna
Tak będzie intuicyjniej - może nie matematycznie, ale dla programisty powinno być

**Comment by BartoszChrostowski** [comment]
Ok, jakiegoś zaćmienia dostałem
